const cfg=window.APP_CONFIG||{};const supabase=window.supabase.createClient(cfg.SUPABASE_URL,cfg.SUPABASE_ANON_KEY);let students=[],selected=null,question=null,token=null,rating=0,adminUser=null;
const $=id=>document.getElementById(id);const show=id=>['rosterView','loginView','dashboardView','adminLoginView','adminView'].forEach(x=>$(x).classList.toggle('hidden',x!==id));const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function load(){try{students=await fetch('data/students.json').then(r=>r.json());$('statusPill').textContent=`${students.length} students`;render(students)}catch(e){$('statusPill').textContent='Data error'}}
function render(list){$('roster').innerHTML=list.map(s=>`<button class="student" data-roll="${esc(s.roll)}"><strong>${esc(s.roll)}</strong><small>${esc(s.name)}</small></button>`).join('');document.querySelectorAll('.student').forEach(b=>b.onclick=()=>select(b.dataset.roll))}
$('search').oninput=e=>{let q=e.target.value.toLowerCase().trim();render(students.filter(s=>s.roll.toLowerCase().includes(q)||s.name.toLowerCase().includes(q)))};$('clearSearch').onclick=()=>{$('search').value='';render(students)};
async function select(roll){selected=students.find(s=>s.roll===roll);token=null;$('studentTitle').textContent=selected.name;$('studentMeta').textContent=`Roll ${selected.roll} • Section ${selected.section}`;$('avatar').textContent=selected.name[0];show('loginView');await newQuestion()}
async function api(path,body={},auth){let headers={'Content-Type':'application/json'};if(auth)headers.Authorization=`Bearer ${auth}`;let r=await fetch(`${cfg.SUPABASE_URL}/functions/v1/${path}`,{method:'POST',headers,body:JSON.stringify(body)});let d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Request failed');return d}
async function newQuestion(){if(!cfg.SUPABASE_URL||cfg.SUPABASE_URL.includes('YOUR_')){$('questionText').textContent='Connect Supabase in config.js first.';return}$('error').textContent='';$('answer').value='';$('refreshQ').disabled=true;try{let d=await api('get-question',{roll:selected.roll});question=d.question;$('questionText').textContent=question.text}catch(e){$('error').textContent=e.message}finally{$('refreshQ').disabled=false}}
$('refreshQ').onclick=newQuestion;$('backBtn').onclick=()=>show('rosterView');$('verifyBtn').onclick=async()=>{let answer=$('answer').value.trim();if(!answer||!question)return;$('verifyBtn').disabled=true;$('error').textContent='';try{let d=await api('authenticate',{roll:selected.roll,question_id:question.id,answer});token=d.token;$('dashName').textContent=selected.name;$('dashMeta').textContent=`Roll ${selected.roll} • Section ${selected.section}`;show('dashboardView')}catch(e){$('error').textContent=e.message;await newQuestion()}finally{$('verifyBtn').disabled=false}};
$('logout').onclick=()=>{token=null;selected=null;rating=0;show('rosterView')};for(let i=1;i<=5;i++){let b=document.createElement('button');b.className='star';b.textContent='★';b.setAttribute('aria-label',`${i} stars`);b.onclick=()=>{rating=i;document.querySelectorAll('.star').forEach((x,j)=>x.classList.toggle('selected',j<i))};$('stars').appendChild(b)}
$('submitRating').onclick=async()=>{if(!rating||!token)return;$('submitRating').disabled=true;try{await api('submit-rating',{rating,feedback:$('feedback').value.trim()},token);$('ratingMsg').textContent='Thanks! Your feedback was submitted.';$('feedback').value='';rating=0;document.querySelectorAll('.star').forEach(x=>x.classList.remove('selected'))}catch(e){$('ratingMsg').textContent=e.message}finally{$('submitRating').disabled=false}};
$('adminOpen').onclick=()=>show('adminLoginView');$('adminBack').onclick=()=>show('rosterView');$('adminLogin').onclick=async()=>{try{$('adminError').textContent='';let {data,error}=await supabase.auth.signInWithPassword({email:$('adminEmail').value.trim(),password:$('adminPassword').value});if(error)throw error;adminUser=data.user;await loadAdmin();show('adminView')}catch(e){$('adminError').textContent=e.message}};$('adminLogout').onclick=async()=>{await supabase.auth.signOut();adminUser=null;show('rosterView')};
async function loadAdmin(){await Promise.all([loadAdminStudents(),loadQuestions(),loadRatings()]);}
async function loadAdminStudents(){let d=await api('admin-students',{action:'list'});students=d.students;renderAdminStudents(d.students);$('statusPill').textContent=`${d.students.length} students`}
function renderAdminStudents(a){$('studentTable').innerHTML=`<table class="data-table"><thead><tr><th>Roll</th><th>Name</th><th>Section</th><th>Questions</th><th></th></tr></thead><tbody>${a.map(s=>`<tr><td>${esc(s.roll)}</td><td>${esc(s.name)}</td><td>${esc(s.section)}</td><td>${s.question_count}</td><td class="actions"><button class="mini" onclick="editStudent('${esc(s.id)}')">Edit</button><button class="mini" onclick="addQuestionFor('${esc(s.id)}')">+ Question</button></td></tr>`).join('')}</tbody></table>`}
async function loadQuestions(){let d=await api('admin-questions',{action:'list'});window.questions=d.questions;renderQuestions(d.questions)}
function renderQuestions(a){$('questionTable').innerHTML=`<table class="data-table"><thead><tr><th>Student</th><th>Question</th><th>Status</th><th></th></tr></thead><tbody>${a.map(q=>`<tr><td>${esc(q.student_name)}<br><span class="muted">${esc(q.roll)}</span></td><td>${esc(q.question_text)}</td><td>${q.active?'Active':'Off'}</td><td class="actions"><button class="mini" onclick="editQuestion('${esc(q.id)}')">Edit</button><button class="mini" onclick="deleteQuestion('${esc(q.id)}')">Delete</button></td></tr>`).join('')}</tbody></table>`}
async function loadRatings(){let d=await api('admin-ratings',{action:'list'});window.ratings=d.ratings;let avg=d.ratings.length?(d.ratings.reduce((a,x)=>a+x.rating,0)/d.ratings.length).toFixed(2):'—';$('stats').innerHTML=`<div class="stat"><span class="muted">Students</span><b>${students.length}</b></div><div class="stat"><span class="muted">Ratings</span><b>${d.ratings.length}</b></div><div class="stat"><span class="muted">Average</span><b>${avg}${avg!=='—'?' / 5':''}</b></div>`;renderRatings(d.ratings)}
function renderRatings(a){$('ratingTable').innerHTML=`<table class="data-table"><thead><tr><th>Student</th><th>Rating</th><th>Feedback</th><th>Date</th></tr></thead><tbody>${a.map(r=>`<tr><td>${esc(r.student_name)}</td><td>${'★'.repeat(r.rating)}${'☆'.repeat(5-r.rating)}</td><td>${esc(r.feedback||'—')}</td><td>${new Date(r.created_at).toLocaleString()}</td></tr>`).join('')}</tbody></table>`}
function modal(title,html){$('modalTitle').textContent=title;$('modalBody').innerHTML=html;$('modal').classList.remove('hidden')}$('modalClose').onclick=()=>$('modal').classList.add('hidden');
$('addStudent').onclick=()=>modal('Add student',`<form class="modal-form" id="studentForm"><label>Roll<input name="roll" required></label><label>Name<input name="name" required></label><label>Section<input name="section" value="D"></label><label>Branch<input name="branch" value="CSM"></label><div class="modal-actions"><button type="submit">Save</button></div></form>`);document.addEventListener('submit',async e=>{if(e.target.id==='studentForm'){e.preventDefault();let f=new FormData(e.target);await api('admin-students',{action:'create',roll:f.get('roll'),name:f.get('name'),section:f.get('section'),branch:f.get('branch')});$('modal').classList.add('hidden');await loadAdminStudents()};if(e.target.id==='questionForm'){e.preventDefault();let f=new FormData(e.target);try{await api('admin-questions',{action:'create',student_id:f.get('student_id'),question_text:f.get('question_text'),answer:f.get('answer')});$('modal').classList.add('hidden');await loadQuestions();await loadAdminStudents()}catch(err){alert(err.message)}}});
window.addQuestionFor=id=>modal('Add private question',`<form class="modal-form" id="questionForm"><input type="hidden" name="student_id" value="${esc(id)}"><label>Question<input name="question_text" placeholder="Private class-related question" required></label><label>Answer<input name="answer" placeholder="Answer (will be hashed)" required></label><div class="modal-actions"><button type="submit">Save question</button></div></form>`);$('addQuestion').onclick=()=>modal('Add private question',`<form class="modal-form" id="questionForm"><label>Student<select name="student_id" required>${students.map(s=>`<option value="${s.id||''}">${esc(s.roll)} — ${esc(s.name)}</option>`).join('')}</select></label><label>Question<input name="question_text" required></label><label>Answer<input name="answer" required></label><div class="modal-actions"><button type="submit">Save question</button></div></form>`);
window.editStudent=async id=>{let s=students.find(x=>x.id===id);if(!s){let d=await api('admin-students',{action:'list'});s=d.students.find(x=>x.id===id)}modal('Edit student',`<form class="modal-form" id="editStudentForm"><input type="hidden" name="id" value="${esc(s.id)}"><label>Roll<input name="roll" value="${esc(s.roll)}" required></label><label>Name<input name="name" value="${esc(s.name)}" required></label><label>Section<input name="section" value="${esc(s.section)}"></label><label>Branch<input name="branch" value="${esc(s.branch)}"></label><div class="modal-actions"><button type="submit">Save</button></div></form>`)};
document.addEventListener('submit',async e=>{if(e.target.id==='editStudentForm'){e.preventDefault();let f=new FormData(e.target);await api('admin-students',{action:'update',id:f.get('id'),roll:f.get('roll'),name:f.get('name'),section:f.get('section'),branch:f.get('branch')});$('modal').classList.add('hidden');await loadAdminStudents()}});
window.editQuestion=async id=>{let q=window.questions.find(x=>x.id===id);modal('Edit question',`<form class="modal-form" id="editQuestionForm"><input type="hidden" name="id" value="${esc(q.id)}"><label>Question<input name="question_text" value="${esc(q.question_text)}" required></label><label>New answer (optional)<input name="answer" placeholder="Leave blank to keep existing answer"></label><label>Active<select name="active"><option value="true" ${q.active?'selected':''}>Active</option><option value="false" ${!q.active?'selected':''}>Off</option></select></label><div class="modal-actions"><button type="submit">Save</button></div></form>`)};
document.addEventListener('submit',async e=>{if(e.target.id==='editQuestionForm'){e.preventDefault();let f=new FormData(e.target);await api('admin-questions',{action:'update',id:f.get('id'),question_text:f.get('question_text'),answer:f.get('answer'),active:f.get('active')==='true'});$('modal').classList.add('hidden');await loadQuestions()}});window.deleteQuestion=async id=>{if(confirm('Delete this question?')){await api('admin-questions',{action:'delete',id});await loadQuestions();await loadAdminStudents()}};$('refreshRatings').onclick=loadRatings;
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.tab-panel').forEach(x=>x.classList.add('hidden'));$(b.dataset.tab).classList.remove('hidden')});load();
